export {objects}
export {actions}

const objects = [
  "Elvis Presley",
  "Spongebob Squarepants",
  "Batman",
  "A baby",
  "Oprah Winfrey",
  "A cat",
  "An owl",
  "Beyonce",
  "Kim Kardashian",
  "A chicken",
  "Santa Claus",
  "A seagull ",
  "A baby",
  "The Hulk",
  "James Bond",
  "A dog",
  "A lion",
  "Lady Gaga",
  "A frog",
  "A monkey",
  "Spider-Man",
  "Superman",
  "Freddie Mercury",
  "A sheep",
  "A horse",
  "The Queen of England",
  "A dolphin squeaking",
  "Thor",
  "A chair",
  "A pair of scissors",
  "A baseball bat",
  "A telephone",
  "A skateboard",
  "A spoon",
  "An egg",
  "A ball",
  "A pencil",
  "A scarf",
  "A key",
  "A witch",
];

const actions = [
  "Jumping",
  "Dancing",
  "Running",
  "Skipping",
  "Singing",
  "Whistling",
  "Laughing",
  "Crying",
  "Screaming",
  "Shouting",
  "Talking",
  "Walking",
  "Climbing",
  "Swimming",
  "Hiking",
  "Boxing",
  "Kicking",
  "Punching",
  "Stretching",
  "Balancing",
  "Skipping rope",
  "Doing push-ups",
  "Doing sit-ups",
  "Lifting weights",
  "Cycling",
  "Skateboarding",
  "Snowboarding",
  "Skiing",
  "Playing football",
  "Playing soccer",
  "Playing tennis",
  "Playing volleyball",
  "Playing golf",
  "Doing yoga",
  "Playing chess",
  "Playing a musical instrument",
  "Painting",
  "Reading",
  "Playing basketball",
  "Doing hockey",
];

